version: '3.8'

services:
  app:
    build: .
    container_name: bank-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/bankDiplome?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    container_name: bank-mysql
    environment:
      - MYSQL_DATABASE=bankDiplome
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ] # Команда проверки
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s